### ISSUE TITLE
[ENH] Implement `cpp_ptb` function for init an un-init

### ISSUE THREAD

**Issue by marcobarilari** [cpp-lln-lab/template_PTB_experiment#30]
### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by Remi-Gau** [comment]
for init changing this line 

https://github.com/cpp-lln-lab/template_PTB_experiment/blob/038bf8540ce81dc00a852da02c97e96d3ecbe770/initEnv.m#L103

to

`run(fullfile(thisDirectory, 'lib', 'CPP_PTB', 'cpp-ptb'));`

**Comment by Remi-Gau** [comment]
for uninit...

it will be more complicated because we have to keep track of the folders added to the path and then remove them

**Comment by Remi-Gau** [comment]
the cleanest implementation we have of this is in bidspm

https://github.com/cpp-lln-lab/bidspm/blob/bf1226515dc75e7a26b4fc1461da2d07ff456c93/bidspm.m#L424

https://github.com/cpp-lln-lab/bidspm/blob/bf1226515dc75e7a26b4fc1461da2d07ff456c93/bidspm.m#L559

and it requires for all the submodules to have a similar way of keeping track of what is added to the path or not

**Comment by marcobarilari** [comment]
not sure I am following. So just adding at the begging of the code `cpp_ptb(init)` and at the end `cpp_ptb(uninit)` will not work?

**Comment by Remi-Gau** [comment]
Yes... but...

It won't remove the stuff added to the path:

here: 

https://github.com/cpp-lln-lab/template_PTB_experiment/blob/038bf8540ce81dc00a852da02c97e96d3ecbe770/initEnv.m#L102

and here:

https://github.com/cpp-lln-lab/template_PTB_experiment/blob/038bf8540ce81dc00a852da02c97e96d3ecbe770/initEnv.m#L104

But defo worth implementing: let's not have perfect be the ennemy of good.

So feel free to PR this.

**Comment by Remi-Gau** [comment]
oh actually...

cpp_bids has an init and uninit too!!

https://github.com/cpp-lln-lab/CPP_BIDS/blob/3a0613e64b2048db0f4a8b97c26722b691e034df/cpp_bids.m#L8

so that could be added in the same PR
